### ISSUE TITLE
[Bug] Installing on server invalid characters in folder name.

### ISSUE THREAD

**Issue by RichardB01** [1NANO/Onset-ObjectInteraction#1]
Hey!

If you put the folder "Onset-ObjectInteraction" into your packages, the server wont load it because it has the character "-" in the name!

Thanks,
Richard

**Comment by 1NANO** [comment]
Once you pulled or downloaded the folder Onset-ObjectInteraction, you need to put the other folder named "ObjectInteraction" inside your packages folder ^^
